name: Pipeline CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurando Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalando dependências
        run: npm install

      - name: Test
        run: npm test

      - name: Enviar e-mail falha
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_ORIGEM }}
          password: ${{ secrets.SENHA_EMAIL }}
          subject: Falha no workflow do GitHub Actions
          body: O workflow falhou no passo de testes.
          to: ${{ secrets.EMAIL_DESTINO }}
          from: ${{ secrets.EMAIL_ORIGEM }}

