name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install  # ou outro comando de instalação, dependendo do seu projeto

    - name: Build
      run: |
        npm run build  # ou outro comando de build

    - name: Run tests
      run: |
        npm test  # ou outro comando de testes

    - name: Send email notification
      run: |
        echo "Sending email notification..."
        echo "Subject: CI Pipeline Notification" | sendmail -v fe.dsm.vot.001@gmail.com

    - name: Versioning
      run: |
        npm version patch  # ou minor/major, conforme necessário
