name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install  

    - name: Build
      run: |
        npm run build  

    - name: Run tests
      run: |
        npm test -- --detectOpenHandles  

    - name: Send email notification
      run: |
        echo "Sending email notification..."
        echo "Subject: CI Pipeline Notification" | sendmail -v fe.dsm.vot.001@gmail.com


    - name: Versioning
      run: |
        npm version patch  
